spotify/confidence-sdk-swift

- CONTRIBUTING.md
- scripts/run_tests.sh
Use this command to store the token:
`security add-generic-password -s 'Swift Provider - E2E Tests'  -a 'konfidens-e2e' -w 'CLIENT_TOKEN'`
> Run tests script can read from keychain for the client token

- ConfidenceDemoApp/ConfidenceDemoApp/ConfidenceDemoApp.swift
- ConfidenceDemoApp/ConfidenceDemoApp/ContentView.swift
- README.md
- Sources/ConfidenceProvider/Cache/DefaultStorage.swift
- Sources/ConfidenceProvider/Cache/Storage.swift
- Sources/ConfidenceProvider/ConfidenceFeatureProvider.swift
- Tests/ConfidenceProviderTests/CacheDataInteractorTests.swift
- Tests/ConfidenceProviderTests/CacheDataTests.swift
- Tests/ConfidenceProviderTests/Helpers/CacheDataUtility.swift
- Tests/ConfidenceProviderTests/Helpers/StorageMock.swift
- Adds a function to check if the storage has something in it.
- Fixes some compiler warnings on unused variables.
- Adds thread safety to Storage mock.
> feat: Storage check

- Sources/ConfidenceProvider/Apply/FlagApplierWithRetries.swift
- Sources/ConfidenceProvider/ConfidenceClient/RemoteConfidenceClient.swift
- Sources/ConfidenceProvider/ConfidenceFeatureProvider.swift
- Sources/ConfidenceProvider/InitializationStrategy.swift
- Sources/ConfidenceProvider/Utils/ConfidenceMetadata.swift
- Tests/ConfidenceProviderTests/FlagApplierWithRetriesTest.swift
- Tests/ConfidenceProviderTests/RemoteConfidenceClientTest.swift
- release-please-config.json
To comply with the updated Confidence APIs
> feat: Add SDK id and version to requests

- .github/workflows/ci.yaml
- CONTRIBUTING.md
- Tests/ConfidenceProviderTests/ConfidenceIntegrationTest.swift
- scripts/run_tests.sh
As we are cleaning up older unused Confidence orgs and moving the testing setup to new ones
> ci: Update IntegrationTest flag

- Sources/ConfidenceProvider/ConfidenceClient/RemoteConfidenceClient.swift
- Sources/ConfidenceProvider/Http/NetworkClient.swift
- Tests/ConfidenceProviderTests/ConfidenceIntegrationTest.swift
- Tests/ConfidenceProviderTests/FlagApplierWithRetriesTest.swift
- Tests/ConfidenceProviderTests/Helpers/HttpClientMock.swift
Previously, the region would default to Europe. This PR is changing this to GLOBAL and is specifying a URL for that.
> fix: add a default endpoint to the provider

- Sources/ConfidenceProvider/Apply/FlagApplierWithRetries.swift
- Sources/ConfidenceProvider/Http/HttpClient.swift
- Sources/ConfidenceProvider/Http/NetworkClient.swift
- Tests/ConfidenceProviderTests/CacheDataInteractorTests.swift
- Tests/ConfidenceProviderTests/Helpers/HttpClientMock.swift
- scripts/run_tests.sh
Issues with flaky tests seem to be caused by the async `apply` function in `FlagApplier` not really waiting for the entire triggerBatch operation to finish (including network + updating the cache for apply status), before returning.
Note: older context around the existing asynchronous setup: https://github.com/spotify/confidence-openfeature-provider-swift/pull/35 (not sure how much this is relevant for this PR)
> fix: Fix FlagApplier async behaviour

- Sources/ConfidenceProvider/Apply/FlagApplierWithRetries.swift
- Sources/ConfidenceProvider/ConfidenceClient/RemoteConfidenceClient.swift
- Sources/ConfidenceProvider/Http/HttpClient.swift
- Sources/ConfidenceProvider/Http/NetworkClient.swift
- Tests/ConfidenceProviderTests/Helpers/HttpClientMock.swift
Streamline the network implementation to use async/await across the entire stack.
> refactor: Remove callbacks from HttpClient

- Sources/ConfidenceProvider/ConfidenceFeatureProvider.swift
The reasons behind this change:
- This is currently not working as expected, since in case of `activateAndFetchAsync` the STALE event is emitted even if it shouldn't
- According to [this WIP Proposal](https://github.com/open-feature/spec/pull/241/files), no event is expected prior to "initialize". 
- The STALE event is not meant to indicate a "not-ready cache" anyway: it's meant be used only if the system detects a change of flag evaluation data (for the same evaluation context). From the same PR mentioned above, a new events will be introduced for context reconciliation: `PROVIDER_CONTEXT_PENDING` and `PROVIDER_CONTEXT_CHANGED`
> fix: Remove STALE event

- Sources/ConfidenceProvider/ConfidenceFeatureProvider.swift
- Tests/ConfidenceProviderTests/ConfidenceFeatureProviderTest.swift
Previously, the provider would emit STALE if the evaluation context changed and the cache has been populated with default values due to fetch request not being finished. We believe that trying to access cache too early is an error on the user's side and should be communicated as an ERROR and not STALE.
> fix: change STALE reason in case of context change

- Sources/Confidence/ConfidenceValue.swift
- Sources/ConfidenceProvider/Utils/ConfidenceTypeMapper.swift
- Tests/ConfidenceProviderTests/ConfidenceTypeMapperTest.swift
- Tests/ConfidenceTests/ConfidenceValueTests.swift
Exploratory PR not meant for merging yet.
> refactor: Restrict heterogeneous ConfidenceValue lists

- Sources/Confidence/ConfidenceClient/RemoteConfidenceClient.swift
- Tests/ConfidenceTests/EventSenderEngineTest.swift
- Tests/ConfidenceTests/EventUploaderMock.swift
- Tests/ConfidenceTests/Helpers/MockedClientURLProtocol.swift
- Tests/ConfidenceTests/RemoteConfidenceClientTests.swift
This PR is adding handling of status codes for the uploader in connection to storing events in storage.
> feat: handle status codes for retrying in uploader

- ConfidenceDemoApp/ConfidenceDemoApp/ConfidenceDemoApp.swift
- Sources/Confidence/Confidence.swift
- Sources/Confidence/ConfidenceEventSender.swift
- Sources/Confidence/EventSenderEngine.swift
- Tests/ConfidenceTests/EventSenderEngineTest.swift
- Tests/ConfidenceTests/Helpers/EventSenderEngineMock.swift
Signature is:
```
public func send(eventName: String, message: ConfidenceStruct) { ... }
```
> refactor: Add message container to payload

- Sources/ConfidenceProvider/ConfidenceClient/ConfidenceClient.swift
- Sources/ConfidenceProvider/ConfidenceClient/LocalStorageResolver.swift
- Sources/ConfidenceProvider/ConfidenceClient/Resolver.swift
- Sources/ConfidenceProvider/ConfidenceFeatureProvider.swift
- Tests/ConfidenceProviderTests/ConfidenceFeatureProviderTest.swift
- Tests/ConfidenceProviderTests/Helpers/ClientMock.swift
- Tests/ConfidenceProviderTests/LocalStorageResolverTest.swift
After a discussion within the team, it has been decided that when context is updated and provider is stale (hasn't resolved with new evaluation context / is about to resolve), in the meantime we would return previous value.
> feat: Return previous value on Provider STALE

- Sources/Confidence/Confidence.swift
- Sources/ConfidenceProvider/ConfidenceFeatureProvider.swift
- Tests/ConfidenceProviderTests/ConfidenceFeatureProviderTest.swift
- Tests/ConfidenceProviderTests/Helpers/FlagApplierMock.swift
Flaky test, but could reproduce this every 3/4 runs:
> fix: Provider cache and resolver are accessed safely

- Sources/Confidence/Confidence.swift
- Sources/Confidence/Contextual.swift
- Tests/ConfidenceTests/ConfidenceTests.swift
This reverts commit 6bdbf95686c09f93fa2b9d0c33fddf6ca0072548.
> fix: Revert "fix: Reconciliation bug"

- ConfidenceDemoApp/ConfidenceDemoApp/ContentView.swift
- Sources/Confidence/Confidence.swift
- Sources/Confidence/ConfidenceEventSender.swift
- Sources/Confidence/EventSenderEngine.swift
- Sources/Confidence/ManualFlushPolicy.swift
- Tests/ConfidenceTests/EventSenderEngineTest.swift
- Tests/ConfidenceTests/EventUploaderMock.swift
- Tests/ConfidenceTests/Helpers/EventSenderEngineMock.swift
We want to allow for the user to manually trigger an upload to the backend services for all events emitted up to that point. 
The approach used in this PR is to treat a call to the `flush()` method as a special event emitted, which will mean that the events in the "write channel" will be guaranteed to have been written to disk (and thus applicable to be part of the "batch" to upload) before the actual flush happens.
> feat: add functionality to manual flush events

- Sources/Confidence/Confidence.swift
- Sources/Confidence/EventSenderEngine.swift
- Tests/ConfidenceTests/EventSenderEngineTest.swift
the write queue will consume one tracked event after the other and write them to disk and run the flush policies
> feat: introduce a writeQueue for event tracking

- Sources/Confidence/ConfidenceAppLifecycleProducer.swift
- Tests/ConfidenceTests/EventSenderEngineTest.swift
- Fix `CONFIDENCE_VERSIONN_KEY` typo
- Add `app_` prefix to version and build contexts
> fix: Improved keys and remove typo

- Sources/Confidence/Confidence.swift
- Sources/Confidence/ConfidenceError.swift
- Sources/Confidence/ConfidenceEventSender.swift
- Sources/Confidence/EventSenderEngine.swift
- Sources/Confidence/PayloadMerger.swift
- Tests/ConfidenceTests/ConfidenceFeatureProviderTest.swift
- Tests/ConfidenceTests/EventSenderEngineTest.swift
- Tests/ConfidenceTests/PayloadMergerTests.swift
Message's `context`'s inner fields are merged with higher prio in the context container
> refactor: `context` container in event payload

- Sources/Confidence/ConfidenceAppLifecycleProducer.swift
- Sources/Confidence/ConfidenceScreenTracker.swift
- Sources/Confidence/EventStorage.swift
- Sources/Confidence/Http/NetworkClient.swift
- Tests/ConfidenceTests/ConfidenceValueTests.swift
- Tests/ConfidenceTests/Helpers/StorageMock.swift
This PR removed is_foreground from AppLifecycleEventProducer.
> refactor: remove is_foreground from event producer

- ConfidenceDemoApp/ConfidenceDemoApp/ConfidenceDemoApp.swift
- Sources/ConfidenceProvider/ConfidenceTypeMapper.swift
- Tests/ConfidenceProviderTests/ConfidenceTypeMapperTest.swift
"targeting_key" was not propagated correctly in this example (i.e. `targeting_key` was set to an empty string):
```
let initCtx = MutableContext(attributes: ["targeting_key": .string("user1")])
await OpenFeatureAPI.shared.setProviderAndWait(
provider: ConfidenceFeatureProvider(
confidence: confidence,
initializationStrategy: InitializationStrategy.fetchAndActivate),
initialContext: initCtx)
```
> fix: targeting_key conversion

- Sources/Confidence/Confidence.swift
- Sources/ConfidenceProvider/ConfidenceFeatureProvider.swift
- Tests/ConfidenceProviderTests/ConfidenceProviderTest.swift
- Tests/ConfidenceTests/ConfidenceContextTests.swift
- Tests/ConfidenceTests/ConfidenceTest.swift
This allows the application to continue on `setProviderAndWait`, instead of waiting indefinitely for a `ready` or `error` local-event that will never be triggered.
> fix: Issues with context/secret trigger error

- Sources/Confidence/Confidence.swift
- Sources/Confidence/RemoteResolveConfidenceClient.swift
- Sources/ConfidenceProvider/ConfidenceFeatureProvider.swift
- Tests/ConfidenceProviderTests/ConfidenceProviderTest.swift
- Tests/ConfidenceTests/ConfidenceTest.swift
> feat: CreateConfidence from Provider for Metadata

- release-please-config.json
Not sure if we should bump manually the wrong version [here](https://github.com/spotify/confidence-sdk-swift/blob/54a674e7ff8be4c97ad296f6bf066b8641ae95b5/Sources/Confidence/Confidence.swift#L316), or release please will fix everything automatically on merge. I think the latter
> fix: Confidence version auto-update

- README.md
- Sources/Confidence/Confidence.swift
- Sources/Confidence/FlagEvaluation.swift
- Sources/ConfidenceProvider/ConfidenceFeatureProvider.swift
- Tests/ConfidenceProviderTests/ConfidenceProviderTest.swift
- Tests/ConfidenceTests/ConfidenceIntegrationTest.swift
- Tests/ConfidenceTests/ConfidenceTest.swift
- Tests/ConfidenceTests/LocalStorageResolverTest.swift
- api/Confidence_public_api.json
It's not consistent if some errors are returned via `errorCode` and `errorMessage` fields and other errors (i.e. flagNotFound) are handled via throwing.
This is also the behaviour in OpenFeature.
> refactor!: getEvaluation doesnt throw

- Sources/Confidence/ConfidenceScreenTracker.swift
- Sources/Confidence/ConfidenceValueHash.swift
- Sources/Confidence/EventSenderEngine.swift
- Sources/Confidence/EventStorage.swift
- Sources/Confidence/Http/NetworkClient.swift
- Tests/ConfidenceProviderTests/ConfidenceProviderTest.swift
- Tests/ConfidenceTests/ConfidenceTest.swift
- Tests/ConfidenceTests/ConfidenceValueTests.swift
- Tests/ConfidenceTests/FlagApplierWithRetriesTest.swift
- Tests/ConfidenceTests/Helpers/StorageMock.swift
This also includes some changes suggested by the static linter.
_Suggestion is to review commit by commit_
> fix: Fix warnings and prevent potential issues

- Tests/ConfidenceProviderTests/ConfidenceTypeMapperTest.swift
- Tests/ConfidenceTests/ConfidenceIntegrationTest.swift
- Tests/ConfidenceTests/ConfidenceValueTests.swift
- Tests/ConfidenceTests/TypeMapperTests.swift
These tests started failing on iOS18. It must be something that has changed in the Apple ecosystem, although I haven't found the exact culprit yet. Nevertheless, specifying the locale is still good practice, and it makes the tests green.
Note that the main code (not the test code), is setting locale already: https://github.com/spotify/confidence-sdk-swift/blob/448fb930e869d8282566f5c1abfa147a1a6611e9/Sources/Confidence/Backport.swift#L64
> test: date formatter in tests iOS18

- Sources/Confidence/FlagEvaluation.swift
- Sources/ConfidenceProvider/ConfidenceFeatureProvider.swift
- Tests/ConfidenceTests/ConfidenceIntegrationTest.swift
- Tests/ConfidenceTests/ConfidenceTest.swift
This is an important fix to signal users that the returned value is the default value due to a type mismatch, rather than looking like the variant's value returned by the backend.
This happens when the user tries to get a value with a type that is not the the same type defined in the backend schema for that value.
> fix: TypeMismatch error is handled

- Sources/Confidence/FlagEvaluation.swift
- Tests/ConfidenceTests/ConfidenceTest.swift
> fix: TypeMismatch doesn't trigger apply

- Sources/Confidence/DebugLogger.swift
`URLComponents` takes care of properly encoding URL query items
> fix: Properly encoded Resolve Debug URL

- Sources/Confidence/DebugLogger.swift
> fix: Align debug resolve log wording on all platforms

- ConfidenceDemoApp/ConfidenceDemoApp.xcodeproj/project.pbxproj
- ConfidenceDemoApp/ConfidenceDemoApp/ConfidenceDemoApp.swift
- Package.resolved
- Package.swift
- Sources/ConfidenceProvider/ConfidenceFeatureProvider.swift
- Tests/ConfidenceProviderTests/ConfidenceProviderTest.swift
- api/ConfidenceProvider_public_api.json
Events are removed, since now handled automatically by the underlying SDK. onContextSet is now awaiting, returning on success or throwing on failure, as expected by the new SDK version.
> feat: Adopt latest OF SDK

- Sources/Confidence/ConfidenceClient.swift
- Sources/Confidence/FlagEvaluation.swift
- Sources/Confidence/RemoteResolveConfidenceClient.swift
- Tests/ConfidenceProviderTests/ConfidenceProviderTest.swift
- Tests/ConfidenceTests/ConfidenceTest.swift
- Tests/ConfidenceTests/Helpers/ClientMock.swift
- Tests/ConfidenceTests/LocalStorageResolverTest.swift
The SDK will use `shouldApply` boolean coming from backend service when sending an apply event.
> feat: add shouldApply to control sending apply

- Sources/Confidence/DebugLogger.swift
- Tests/ConfidenceTests/DebugLoggerTests.swift
Resolver hint logs will now contain a base64 encoded string which can be pasted in the Confidence tools to support that we don't necessarily know the URL the user would want to use.
Had to change the "scope" of the DebugLogger in order to unit test this properly. We can restore it if we remove the tests.
> fix: change how we log resolve tester hints

- .github/workflows/ci.yaml
External contributions would fail in CI if we don't allow for secrets. Error:
```
Run webfactory/ssh-agent@v0.7.0
Error: The ssh-private-key argument is empty. Maybe the secret has not been configured, or you are using a wrong secret name in your workflow file.
```
Example of affected PR: https://github.com/spotify/confidence-sdk-swift/pull/195
> ci: Run with secrets on external PRs

- Package.resolved
- Package.swift
This was needed with https://github.com/spotify/confidence-sdk-swift/pull/198
(Looks like [this](https://github.com/spotify/confidence-sdk-swift/pull/197) runs CI from main, rather than the PR setup, hence pr 198 was green)
> ci: Switch to http in Package

- .github/workflows/ci.yaml
#197 introduced an issue where build and test would run the master code, not the PR code. The reason for #197 was to be able to run workflows with secrets even from external contributions (after approving)
> ci: Build and test PR code

- README.md
- Sources/Confidence/FlagEvaluation.swift
- Sources/Confidence/StructMerger.swift
- Tests/ConfidenceProviderTests/ConfidenceProviderTest.swift
- Tests/ConfidenceTests/ConfidenceIntegrationTest.swift
- Tests/ConfidenceTests/ConfidenceTest.swift
- Tests/ConfidenceTests/FlagEvaluationDictionaryTest.swift
- #193 accidentally removed the capability of using `ConfidenceStruct` as default value for complex evaluations. This PR restores that capability.
- It also improves the logic for `null` entries in the remote variant: the default value for those entries is used, rather than null. This also aligns with the new behavior from the Dictionary-based evaluations. **This is a backwards incompatible change, despite probably minor**
- The Dictionary / OpenFeature complex evaluations are also aligned with the ConfidenceStruct merging logic
> feat!: fix: Restore ConfidenceStruct evals, align Dictionary evals

- Sources/ConfidenceProvider/ConfidenceFeatureProvider.swift
- Sources/ConfidenceProvider/ConfidenceTypeMapper.swift
The original crash was due to this line
```
let newKeys = Set(newContext.asMap().keys)  // CRASH: Dictionary.Keys is not thread-safe
```
By wrapping the keys into an Array, we create a thread-safe snapshot of the keys that can be safely used to instantiate the Set.
More changes in the PR are introduced to try reduce the risk of data inconsistency (not crash-risk race conditions), by creating the `newContextMap` map once and passing that down the chain.
> fix: Race condition and possible data inconsistencies

- Sources/Confidence/ConfidenceClient.swift
- Tests/ConfidenceTests/DefaultStorageTest.swift
We observed crashes with decoding error due to "no associate value for key shouldApply". We think the decoder is trying to read values stored prior to when the `shouldApply` key has been introduced.
The default `true` in these remote cases is acceptable, as over-reporting exposure is not detrimental to the validity of the data.
> fix: ShouldApply backwards compatibility
